version: '3.6'

services:
  # sapper:
  #   build: sapper
  #   command: >
  #     /bin/sh -c "
  #       yarn install --pure-lockfile;
  #       yarn run dev;
  #     "
  #   depends_on:
  #     - graphql
  #     - mail
  #   volumes:
  #     - ./sapper/src:/app/src
  #     - ./sapper/static:/app/static
  #     - ./sapper/package.json:/app/package.json
  #     - ./sapper/yarn.lock:/app/yarn.lock
  #     - ./sapper/webpack.config.js:/app/webpack.config.js
  #     - ./.sapper-cache:/usr/local/share/.cache/yarn/v1
  #   environment:
  #     NODE_ENV: development

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_HOSTNAME: members-mail-1.dev.dock

networks:
  default:
    external:
      name: dev