version: '3.6'

services:
  sapper:
    image: $CI_REGISTRY_IMAGE:latest
    depends_on:
      - graphql
    environment:
      JWT_SECRET: $JWT_SECRET
      NODE_ENV: production
      GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT
      GRAPHQL_URI: $GRAPHQL_URI
