version: '3.6'
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data

  graphql:
    image: hasura/graphql-engine:latest
    ports:
    - "80"
    depends_on:
    - "postgres"
    restart: always
    command: >
      /bin/sh -c "
      graphql-engine \
        --host postgres \
        --port 5432 \
        --user $POSTGRES_USER \
        --password $POSTGRES_PASSWORD \
        --dbname $POSTGRES_DB \
        serve \
        --server-port 80 \
        --access-key $ACCESS_KEY \
        --jwt-secret $$JWT_SECRET \
        --enable-console;
      "

    environment:
      JWT_SECRET: $JWT_SECRET

  auth:
    build: ./auth-service
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT
      JWT_SECRET: $JWT_SECRET
    volumes:
      - ./auth-service/app:/app

volumes:
  db_data:

networks:
  default:
    external:
      name: auth